services:
  postgres:
    image: postgres:17-alpine3.22
    container_name: rinha_backend_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rinha_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  rabbitmq:
    image: rabbitmq:4.1.2-alpine
    container_name: rinha_backend_rabbitmq
    hostname: localhost
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/

volumes:
  postgres_data:
  rabbitmq_data: